name = "LeonExperiments"
uuid = "73de778f-2a0a-4025-929e-85e46414db7c"
authors = ["Leon Riley <114745825+Leonril@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Comodo = "59095408-2761-4f7a-bdc2-044e78630271"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"

[compat]
FileIO = "1.17.1"
GLMakie = "0.13.6"
GeometryBasics = "0.5.10"
MeshIO = "0.5.3"
